# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://valentine022.github.io/valentinepatterson.github.io/'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: https://valentine022.github.io/valentinepatterson.github.io/

# Valentine Patterson
title: Valentine Patterson
# Description of the Site
description: Evolutionary and Computational Biologist
# URL of Image of the Site
site-image: /Users/valentine/valentinepatterson.github.io/IMG_1915.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /Users/valentine/valentinepatterson.github.io/IMG_1915.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: v.patterson02@gmail.com
#facebook_username: thedevslot
#twitter_username: thedevslot
#instagram_username: thedevslot
linkedin_username: https://www.linkedin.com/in/dr-valentine-patterson-8b6b03108/
github_username:  https://github.com/Valentine022
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Valentine Patterson

# Name of the Author
author-name: Valentine Patterson
# URL for the Image of the Author
author-image: /Users/valentine/valentinepatterson.github.io/IMG_4371.JPG
# 60 Words About the Author
author-about:Zoology with a professional training year graduate from Cardiff University. I undertook an Ecology and Evolutionary Genomics MSc at Queen Mary University of London, working on a research project on the molecular diagnostics of pollinator health. I was awarded a PhD at the Johanes Gutenberg University, Mainz, on investigating the genetic and epigenetic diversity in clonal whiptail lizards. I am interested in using molecular and bioinformatic techniques to investigate a phenotypic differences and changes cause by a changing environement, in a range of organisms.  
# URL to the Author's Profile (i.e., Github, Twitter)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
