# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://valentine022.github.io/valentinepatterson.github.io/'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 'https://valentine022.github.io/valentinepatterson.github.io/'

# Valentine Patterson
title: Valentine Patterson
# Description of the Site
description: Evolutionary and Computational Biologist
# URL of Image of the Site
site-image: https://github.com/Valentine022/valentinepatterson.github.io/blob/c37924879160a435f5724a35d8aa25c3e5a2fdcd/assets/images/IMG_1915.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /Users/valentine/valentinepatterson.github.io/IMG_1915.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: v.patterson02@gmail.com
facebook_username:
twitter_username:
instagram_username:
linkedin_username: https://www.linkedin.com/in/dr-valentine-patterson-8b6b03108/
github_username:  https://github.com/Valentine022
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Valentine Patterson

# Name of the Author
author-name: About Me
# URL for the Image of the Author
author-image: /Users/valentine/valentinepatterson.github.io/IMG_4371.JPG
# 60 Words About the Author
author-about: Having completed my undergraduate studies in Zoology at Cardiff University, I embarked on a journey of academic exploration and professional development. My postgraduate endeavors led me to Queen Mary University of London, where I pursued an MSc in Ecology and Evolutionary Genomics. During this period, I delved into the intricacies of molecular diagnostics, focusing particularly on assessing pollinator health—a critical aspect of ecosystem dynamics. \n Building upon my MSc experience, I further developed my research skills through a PhD program at Johanes Gutenberg University, Mainz. My doctoral research centered on unraveling the genetic and epigenetic diversity within clonal whiptail lizards, providing valuable insights into the mechanisms driving evolutionary adaptation in reptilian populations. \n Driven by a passion for understanding the complexities of biological systems, I am deeply interested in using molecular and bioinformatic tools to unravel the phenotypic responses of organisms to environmental changes. Through my interdisciplinary approach, I aspire to contribute meaningfully to the fields of ecology and evolutionary biology, with a focus on enhancing conservation efforts and fostering resilience in natural ecosystems.
# URL to the Author's Profile (i.e., Github, Twitter)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
